name: Build Debian loong64 live cd

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  debian:
    name: Build go toolchain for ABI1.0
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Go environment
        uses: actions/setup-go@v5.5.0
          
      - name: Build go
        id: build_go
        run: |
          cd src
          bash all.bash
          cd ..
          goversion=$(head -n 1 VERSION)
          cd ..
          tar -zcvf "$goversion-linux-amd64.tar.gz" go-loongarch-oldworld


      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Debian loong64 live cd
          path: ${{ github.workspace }}/../*.tar.gz
          compression-level: 0
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

      - name: Upload assets to release
        uses: softprops/action-gh-release@v2
        with:
            files: ${{ github.workspace }}/../*.tar.gz
            prerelease: false
